export const USER_LOGIN_PENDING = 'USER_PENDING';
export const USER_LOGIN_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_SUCESS = 'USER_SUCESS';
export const USER_LOGIN_ERROR = 'USER_ERROR';

export const USER_REGISTER_PENDING = 'USER_REGISTER_PENDING';
export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_ERROR = 'USER_REGISTER_ERROR';